export interface Opportunity {
  description: string;
  id: string;
  title: string;
}

// Two independent marquee rows. Order within each row is the order the
// circles appear in the strip before it loops.
export const ROW_ONE: Opportunity[] = [
  {
    id: "asset",
    title: "Asset Tokenization",
    description:
      "Tokenize physical assets such as real estate, gold, oil reserves, mines, factories, agricultural projects, and other tangible holdings. Asset tokenization enables fractional ownership, improves liquidity, expands investor access, and transforms traditionally illiquid assets into globally accessible investment opportunities.",
  },
  {
    id: "equity",
    title: "Equity Tokenization",
    description:
      "Represent company ownership through blockchain-based tokens. Equity tokenization can modernize fundraising, simplify shareholder management, increase transparency, and allow investors to participate in business growth through digitally managed ownership structures.",
  },
  {
    id: "revenue",
    title: "Revenue Tokenization",
    description:
      "Convert revenue generated by a project, business, platform, or asset into digital tokens. Revenue tokenization enables businesses to raise capital, share future earnings, and create new investment opportunities linked directly to economic performance.",
  },
  {
    id: "loan",
    title: "Loan Tokenization",
    description:
      "Transform loans and financing agreements into blockchain-based assets that can be managed, transferred, monitored, or distributed more efficiently. Loan tokenization can increase transparency, improve liquidity, and streamline financing operations.",
  },
  {
    id: "receivables",
    title: "Receivables Tokenization",
    description:
      "Convert invoices, trade receivables, and outstanding payments into digital assets. Businesses can unlock liquidity from future payments, improve cash flow, and gain access to alternative financing solutions through tokenized receivable structures.",
  },
  {
    id: "debt",
    title: "Debt Tokenization",
    description:
      "Digitize bonds, sukuk, debt instruments, and financial obligations through blockchain infrastructure. Debt tokenization can reduce issuance costs, improve settlement efficiency, increase transparency, and broaden investor participation.",
  },
  {
    id: "fund",
    title: "Fund Tokenization",
    description:
      "Transform investment funds and managed portfolios into digital investment vehicles. Fund tokenization can simplify access for investors, improve transparency, automate administration, and create more liquid investment structures.",
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property Tokenization",
    description:
      "Tokenize intellectual property assets such as software, patents, trademarks, brands, music rights, films, books, and digital content. This model enables creators and organizations to monetize intellectual property in new ways while expanding ownership and investment opportunities.",
  },
  {
    id: "future-cash-flow",
    title: "Future Cash Flow Tokenization",
    description:
      "Convert expected future income streams into investable digital assets. Businesses, infrastructure projects, and commercial operations can access capital today based on projected future cash flows and economic performance.",
  },
  {
    id: "infrastructure",
    title: "Infrastructure Tokenization",
    description:
      "Tokenize large-scale infrastructure projects such as airports, ports, power plants, data centers, transportation systems, utilities, and public development projects. Infrastructure tokenization can attract private capital, improve project financing, and expand investor participation in long-term development initiatives.",
  },
  {
    id: "stablecoin",
    title: "Stablecoin Tokenization",
    description:
      "Create blockchain-based digital currencies backed by stable assets such as fiat currencies, gold, commodities, or other reserve assets. Stablecoin tokenization can support payments, settlements, treasury management, cross-border transactions, and digital financial ecosystems.",
  },
  {
    id: "payment",
    title: "Payment Tokenization",
    description:
      "Tokenize payment systems and transactional networks to facilitate faster, more transparent, and more efficient transfers of value. Payment tokenization can support consumer payments, merchant settlements, B2B transactions, and global commerce.",
  },
  {
    id: "exchange",
    title: "Exchange Tokenization",
    description:
      "Build token-powered exchanges, trading platforms, and liquidity ecosystems where users, investors, and stakeholders participate in platform growth through blockchain-based economic models and incentive structures.",
  },
  {
    id: "liquidity",
    title: "Liquidity Tokenization",
    description:
      "Represent ownership and participation in liquidity pools, automated market makers (AMMs), and trading ecosystems through digital assets. Liquidity tokenization enables more flexible participation in decentralized financial markets.",
  },
  {
    id: "defi",
    title: "DeFi Tokenization",
    description:
      "Tokenize decentralized financial services such as staking, lending, borrowing, yield generation, liquidity provision, and on-chain financial products. This model enables programmable and transparent financial ecosystems without traditional intermediaries.",
  },
];

export const ROW_TWO: Opportunity[] = [
  {
    id: "utility",
    title: "Utility Tokenization",
    description:
      "Create digital assets that provide access to products, services, subscriptions, memberships, software features, or platform capabilities. Utility tokenization can strengthen user engagement while creating sustainable platform economies.",
  },
  {
    id: "governance",
    title: "Governance Tokenization",
    description:
      "Tokenize voting rights and decision-making authority within a project, platform, organization, or ecosystem. Governance tokenization enables stakeholders to participate directly in the evolution and management of decentralized systems.",
  },
  {
    id: "nft",
    title: "NFT Tokenization",
    description:
      "Represent unique digital assets through blockchain technology. NFT tokenization can be applied to digital art, collectibles, memberships, certificates, exclusive content, virtual goods, and other one-of-a-kind assets.",
  },
  {
    id: "gaming",
    title: "Gaming Tokenization",
    description:
      "Tokenize in-game currencies, items, equipment, rewards, skins, characters, and virtual assets. Gaming tokenization allows players to own, trade, monetize, and interact with digital assets across gaming ecosystems.",
  },
  {
    id: "metaverse",
    title: "Metaverse Tokenization",
    description:
      "Tokenize virtual land, digital properties, virtual businesses, identities, and metaverse economies. Metaverse tokenization enables ownership and economic participation within immersive digital environments.",
  },
  {
    id: "social",
    title: "Social Tokenization",
    description:
      "Transform communities, fan bases, memberships, and social ecosystems into token-powered networks. Social tokenization can strengthen engagement, incentivize participation, and create shared economic value between communities and organizations.",
  },
  {
    id: "creator",
    title: "Creator Tokenization",
    description:
      "Enable creators, influencers, artists, educators, and public figures to build tokenized economies around their content, brand, audience, and future growth. Creator tokenization introduces new ways to engage supporters and generate revenue.",
  },
  {
    id: "loyalty",
    title: "Loyalty Tokenization",
    description:
      "Modernize customer loyalty programs by transforming points, memberships, and rewards into blockchain-based assets. Loyalty tokenization can improve engagement, retention, interoperability, and customer participation.",
  },
  {
    id: "reward",
    title: "Reward Tokenization",
    description:
      "Tokenize incentives, achievements, contributions, and performance-based rewards for customers, employees, communities, and ecosystem participants. Reward tokenization creates transparent and scalable incentive systems.",
  },
  {
    id: "identity",
    title: "Identity Tokenization",
    description:
      "Represent digital identities, credentials, certifications, licenses, and verification records on blockchain infrastructure. Identity tokenization can improve security, privacy, trust, and authentication across digital ecosystems.",
  },
  {
    id: "data",
    title: "Data Tokenization",
    description:
      "Transform valuable datasets, information resources, analytics, and digital knowledge assets into tokenized products and services. Data tokenization enables controlled access, monetization, and transparent ownership of information assets.",
  },
  {
    id: "carbon-credit",
    title: "Carbon Credit Tokenization",
    description:
      "Digitize carbon credits and environmental assets to improve transparency, traceability, and accessibility within sustainability markets. Carbon credit tokenization can help organizations participate more efficiently in environmental initiatives.",
  },
  {
    id: "carbon-offset",
    title: "Carbon Offset Tokenization",
    description:
      "Tokenize projects focused on carbon reduction, environmental restoration, reforestation, renewable energy, and sustainability. Carbon offset tokenization can increase transparency and investor participation in climate-focused initiatives.",
  },
  {
    id: "natural-resource",
    title: "Natural Resource Tokenization",
    description:
      "Transform natural resources such as water rights, forests, fisheries, agricultural reserves, energy reserves, and environmental assets into digital investment and management structures. Natural resource tokenization can improve transparency, stewardship, and capital access.",
  },
  {
    id: "human-capital",
    title: "Human Capital Tokenization",
    description:
      "Create tokenized models around professional contracts, future earnings, talent development, athlete agreements, entertainment projects, and individual economic potential. Human capital tokenization introduces innovative approaches to financing careers, performance, and personal growth.",
  },
];
